### ISSUE TITLE
Better modularity in scripts.

### ISSUE THREAD

**Issue by natir** [makapuf/bitbox#27]
In script directory we have some good script but the are write in python 2.7(I am not sure but I think), and they haven't good argument interface. 

I can rewrite this script, but I want to be sure, no big change on this script is plan, and this is a good idea.

**Comment by makapuf** [comment]
Hi @natir, I guess it depends on which script you're talking about.

by python 2.7, do you mean to port it to 3.4 ? be careful that PIL, the used lib for graphics, is currently not released for 3. A port to PILLOW can be done but the interface is a little different and maybe not available everywhere. Python 2.7 is still more deployed than 3.4 (python2 is default on Fedora, Ubuntu and Debian by example).

for the argument interface, yes that's sth I didn't implement for all of them because the interface has not been proved - i.e. not used in sufficiently enough games-. this can be improved for sure.

What scripts are you using ? by example the sprite generating ones need (and are seeing a bit of work on my side), but I'm adding other new elements. 

Maybe it'd be good to know which are used and should have a stable version and which are still not used (or planned to use) and can be upgraded / used on a game by game basis.

**Comment by pulkomandy** [comment]
Python 3 is also not available for Haiku, so I'm happy with staying at 2.7.

**Comment by makapuf** [comment]
Natir, I'll assign this to you if you want, please close if you think it's OK

**Comment by makapuf** [comment]
closing for now, please reopen if you think it's due
